App\Entity\Location:
    properties:
        country:
            - NotBlank: { message: 'Please select a country.', groups: ['create','edit'] }
            - Length:
                  min: 2
                  max: 2
                  minMessage: 'Country code must be {{ limit }} characters.'
                  maxMessage: 'Country code must be {{ limit }} characters.'
                  groups: ['create','edit']

        city:
            - NotBlank: { message: 'Please enter a city.', groups: ['create','edit'] }
            - Length:
                  min: 2
                  max: 100
                  minMessage: 'City must be at least {{ limit }} characters long.'
                  maxMessage: 'City cannot be longer than {{ limit }} characters.'
                  groups: ['create','edit']

        latitude:
            - NotNull: { message: 'Please enter latitude.', groups: ['create','edit'] }
            - Type:    { type: numeric, message: 'Please enter a number.', groups: ['create','edit'] }
            - Range:
                  min: -90
                  max: 90
                  notInRangeMessage: 'Latitude must be between {{ min }} and {{ max }}.'
                  groups: ['create','edit']

        longitude:
            - NotNull: { message: 'Please enter longitude.', groups: ['create','edit'] }
            - Type:    { type: numeric, message: 'Please enter a number.', groups: ['create','edit'] }
            - Range:
                  min: -180
                  max: 180
                  notInRangeMessage: 'Longitude must be between {{ min }} and {{ max }}.'
                  groups: ['create','edit']
